spring.application.name=ifachados
spring.datasource.url=jdbc:mysql://localhost:3306/ifachados
spring.datasource.username=root
spring.datasource.password=ads_2_2026@@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=k;(eR6H.h9%60;"i+$7AoEJQ#.8&ihfU