spring.application.name=ifachados
spring.datasource.url=jdbc:mysql://localhost:3306/ifachados
spring.datasource.username=root
spring.datasource.password=ads_2_2026@@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=troque_essa_chave_por_algo_bem_grande_e_aleatorio_antes_de_producao_9k2m